/// Flutter icons CustomUisIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomUisIcons
///      fonts:
///       - asset: fonts/CustomUisIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomUisIcons {
  CustomUisIcons._();

  static const _kFontFam = 'CustomUisIcons';
  static const String? _kFontPkg = null;

  static const IconData block = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_bold = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_strong = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_return = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outline_problem_alert = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_bold = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_facebook = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solid_person = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solid_user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData todo_list = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_telephone = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user_plus = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_bell = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_left = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_dislike = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_problem_alert = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_building = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_error = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_like = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_ok = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_fluent = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_bold = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_strong = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_user = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloathing = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_outline = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_outline = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_outline = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_outline_active = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_strong = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facilitador = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geometry_icon = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_local = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images_cards = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_hand = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_icon = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_photo = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_simple = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notebook = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_square = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_key = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ph_pencil_fillicons = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_outline = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_icon = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_left = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_right = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uis_ads_icon = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_tool = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData advertising = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus_squared = IconData(0xf0d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus = IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
